services:
  pg:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: analytics
    ports: [ "5432:5432" ]
    volumes:
      - pg_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n
    ports: [ "5678:5678" ]
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    volumes:
      - n8n_data:/home/node/.n8n
      - ../data:/data:ro 
volumes:
  pg_data: {}
  n8n_data: {}
